import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { ArrowRight, ArrowUpRight, Boxes, CalendarDays, FileText, Plus, ReceiptText, TrendingUp, TriangleAlert, UsersRound } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api, currency, dateTime, errorText, printPdf } from '../lib/api';
import { Button } from '../components/ui/button';

export default function Dashboard() {
  const [data, setData] = useState(null); const [inquiries, setInquiries] = useState([]); const navigate = useNavigate();
  useEffect(() => { api.get('/reports/overview').then(r => setData(r.data)).catch(() => {}); api.get('/inquiries').then(r => setInquiries(r.data)).catch(() => {}); }, []);
  const stats = data ? [
    { title: "TODAY'S SALES", value: currency(data.todaySales), note: `Yesterday ${currency(data.yesterdaySales)}`, icon: TrendingUp, tone: 'amber', id: 'today-sales' },
    { title: 'BILLS TODAY', value: String(data.todayBills).padStart(2, '0'), note: 'Completed invoices', icon: ReceiptText, tone: 'blue', id: 'today-bills' },
    { title: 'OPEN QUOTATIONS', value: String(data.pendingQuotes).padStart(2, '0'), note: 'Waiting for a decision', icon: FileText, tone: 'green', id: 'pending-quotes' },
    { title: 'LOW / UNCOUNTED STOCK', value: String(data.lowStock).padStart(2, '0'), note: 'Review inventory counts', icon: TriangleAlert, tone: 'red', id: 'low-stock' },
  ] : [];
  return <div className="dashboard-page" data-testid="dashboard-page"><div className="page-title-row dashboard-title"><div><div className="eyebrow amber">THE STORE AT A GLANCE</div><h1>Good to see you<span className="title-dot">.</span></h1><p>Here's what's happening across your store today.</p></div><span className="today-chip" data-testid="dashboard-today-date"><CalendarDays size={16}/>{new Intl.DateTimeFormat('en-IN', { dateStyle: 'long', timeZone: 'Asia/Kolkata' }).format(new Date())}</span></div>
    <div className="dashboard-stats">{stats.length ? stats.map((s, i) => <div className={`stat-card ${s.tone}`} key={s.id} data-testid={`stat-${s.id}`}><div className="stat-top"><span>{s.title}</span><s.icon size={19}/></div><strong>{s.value}</strong><small>{s.note}</small><span className="stat-index">0{i + 1}</span></div>) : [1,2,3,4].map(i => <div className="stat-card skeleton-card" key={i} data-testid={`dashboard-loading-stat-${i}`}/>)}</div>
    <div className="dashboard-grid"><section className="dashboard-chart" data-testid="dashboard-sales-chart"><div className="dash-section-head"><div><span className="eyebrow">SALES PERFORMANCE</span><h2>Last 7 days</h2></div><span className="chart-legend"><i/> Sales (₹)</span></div><div className="chart-wrap">{data && <ResponsiveContainer width="100%" height="100%"><BarChart data={data.trend} margin={{ top: 10, right: 8, left: -17, bottom: 0 }}><CartesianGrid stroke="#E2E8F0" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="date" tickFormatter={v => new Date(v + 'T12:00:00').toLocaleDateString('en-IN', { weekday: 'short' })} axisLine={false} tickLine={false} tick={{ fill: '#64748B', fontSize: 11 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: '#64748B', fontSize: 11 }} tickFormatter={v => v >= 1000 ? `${Math.round(v / 1000)}k` : v}/><Tooltip cursor={{ fill: '#F1F5F9' }} contentStyle={{ background: '#fff', color: '#0F172A', border: '1px solid #E2E8F0', borderRadius: 12, boxShadow: '0 8px 24px rgba(15,23,42,.08)' }} formatter={v => currency(v)} labelFormatter={v => new Date(v + 'T12:00:00').toLocaleDateString('en-IN', { dateStyle: 'medium' })}/><Bar dataKey="sales" radius={[6,6,0,0]} maxBarSize={42}>{data.trend.map((d,i) => <Cell key={i} fill={i === 6 ? '#2563EB' : '#BFDBFE'}/>)}</Bar></BarChart></ResponsiveContainer>}</div></section><section className="quick-actions" data-testid="dashboard-quick-actions"><div className="dash-section-head"><div><span className="eyebrow">ONE CLICK AWAY</span><h2>Quick actions</h2></div><ArrowUpRight size={18}/></div><button className="quick-action featured" data-testid="dashboard-create-bill-button" onClick={() => navigate('/admin/billing')}><span><ReceiptText size={23}/></span><div><strong>Start a new bill</strong><small>Get your customer checked out.</small></div><ArrowRight size={18}/></button><button className="quick-action" data-testid="dashboard-create-quote-button" onClick={() => navigate('/admin/quotations?new=1')}><span><FileText size={22}/></span><div><strong>Create quotation</strong><small>Put together a winning quote.</small></div><ArrowRight size={18}/></button><button className="quick-action" data-testid="dashboard-add-product-button" onClick={() => navigate('/admin/inventory/new')}><span><Boxes size={22}/></span><div><strong>Add to inventory</strong><small>Keep your catalogue up to date.</small></div><ArrowRight size={18}/></button><div className="quick-status"><span className="status-light"/> {data?.totalProducts ?? '—'} products in your catalogue</div></section></div>
    <div className="dashboard-grid lower"><section className="recent-activity"><div className="dash-section-head"><div><span className="eyebrow">WHAT'S BEEN HAPPENING</span><h2>Recent bills</h2></div><button data-testid="dashboard-view-reports-button" onClick={() => navigate('/admin/reports')}>View reports <ArrowRight size={15}/></button></div><div className="activity-list">{data?.recentBills?.length ? data.recentBills.map(b => <div className="activity-row clickable" key={b.id} data-testid={`recent-bill-${b.id}`} onClick={() => navigate(`/admin/bills/${b.id}`)}><span className="activity-icon"><ReceiptText size={19}/></span><div><strong>{b.customerName || 'Walk-in Customer'}</strong><small>{b.number} · {dateTime(b.date)}</small></div><strong>{currency(b.grandTotal)}</strong><button title="Print bill" aria-label={`Print bill ${b.number}`} data-testid={`recent-bill-print-${b.id}`} onClick={e => { e.stopPropagation(); printPdf(`/billing/${b.id}/pdf?format=thermal`, `${b.number}.pdf`, null, b.number).catch(err => toast.error(errorText(err))); }}><ArrowUpRight size={16}/></button></div>) : <div className="dashboard-empty">No bills yet. Your first sale is just around the corner.</div>}</div></section><section className="top-products"><div className="dash-section-head"><div><span className="eyebrow">THE CUSTOMER'S FAVORITES</span><h2>Top products</h2></div></div>{data?.topProducts?.length ? data.topProducts.slice(0,5).map((p,i) => <div className="top-product-row" key={p.name}><span>{String(i + 1).padStart(2,'0')}</span><strong>{p.name}</strong><small>{p.quantity} sold</small></div>) : <div className="dashboard-empty">Your bestsellers will appear here as you bill.</div>}{inquiries.length > 0 && <div className="inquiry-summary"><span>NEW ENQUIRIES</span><strong>{inquiries.length}</strong><small>Latest: {inquiries[0].name} · {inquiries[0].phone}</small></div>}</section></div>
  </div>;
}