import React, { useEffect, useState } from 'react';
import { BarChart, Bar, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { toast } from 'sonner';
import { CalendarDays, Download, FileText, Printer, TrendingUp, TriangleAlert } from 'lucide-react';
import { api, currency, dateOnly, errorText } from '../lib/api';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';

const tabs = [['sales','Sales'],['products','Products'],['categories','Categories'],['gst','GST'],['stock','Stock'],['customers','Customers'],['quotations','Quotations']];

export default function Reports() {
  const [tab, setTab] = useState('sales'); const [range, setRange] = useState('month');
  const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState('');
  const [overview, setOverview] = useState(null); const [daily, setDaily] = useState(null); const [monthly, setMonthly] = useState(null); const [period, setPeriod] = useState(null);
  const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [gst, setGst] = useState(null); const [stock, setStock] = useState(null); const [customers, setCustomers] = useState(null); const [quotes, setQuotes] = useState(null);
  useEffect(() => { api.get('/reports/overview').then(r => setOverview(r.data)).catch(() => {}); }, []);
  useEffect(() => { const now = new Date(); const today = now.toLocaleDateString('en-CA', { timeZone: 'Asia/Kolkata' }); const start = range === 'today' ? today : range === 'week' ? new Date(Date.now() - 6 * 86400000).toISOString().slice(0,10) : `${today.slice(0,7)}-01`; const from = range === 'custom' ? fromDate : start; const to = range === 'custom' ? toDate : today; const params = { fromDate: from, toDate: to };
    const request = (path, update) => api.get(path).then(r => update(r.data)).catch(err => toast.error(errorText(err)));
    if (tab === 'sales') { request(`/reports/daily?date=${to}`, setDaily); request(`/reports/monthly?month=${today.slice(0,7)}`, setMonthly); request(`/reports/sales?${new URLSearchParams(params)}`, setPeriod); }
    if (tab === 'products') request(`/reports/products?${new URLSearchParams(params)}`, setProducts);
    if (tab === 'categories') request(`/reports/categories?${new URLSearchParams(params)}`, setCategories);
    if (tab === 'gst') request(`/reports/gst?${new URLSearchParams(params)}`, setGst);
    if (tab === 'stock') request('/reports/stock', setStock);
    if (tab === 'customers') request('/reports/customers', setCustomers);
    if (tab === 'quotations') request('/reports/quotations', setQuotes);
  }, [tab, range, fromDate, toDate]);
  const downloadCsv = () => { let headers = []; let rows = []; if (tab === 'products') { headers = ['Product','Quantity','Revenue']; rows = products.map(p => [p.name,p.quantity,p.revenue]); } else if (tab === 'categories') { headers = ['Category','Quantity','Revenue']; rows = categories.map(c => [c.category,c.quantity,c.revenue]); } else if (tab === 'stock') { headers = ['Product','SKU','Stock','Minimum','Purchase price']; rows = (stock?.items || []).map(p => [p.name,p.sku,p.currentStock,p.minStockLevel,p.purchasePrice]); } else if (tab === 'sales') { headers = ['Invoice','Date','Customer','Total','Tax']; rows = (period?.bills || []).map(b => [b.number,b.date,b.customerName,b.grandTotal,b.totalTax]); } else { headers = ['Metric','Value']; rows = Object.entries(tab === 'gst' ? gst || {} : tab === 'customers' ? customers || {} : quotes || {}).filter(([,v]) => typeof v !== 'object'); }
    const content = [headers, ...rows].map(row => row.map(cell => `"${String(cell ?? '').replaceAll('"', '""')}"`).join(',')).join('\n'); const blob = new Blob(['\ufeff' + content], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); const url = URL.createObjectURL(blob); link.href = url; link.download = `asian-${tab}-report.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 5000); };
  return <div className="page-wrap reports-page" data-testid="reports-page"><div className="page-title-row"><div><div className="eyebrow amber">KNOW YOUR NUMBERS</div><h1>Reports<span className="title-dot">.</span></h1><p>Clarity for every decision you make.</p></div><div className="page-title-actions"><Button variant="outline" data-testid="reports-print-button" onClick={() => window.print()}><Printer size={16}/> Print</Button><Button variant="outline" data-testid="reports-export-button" onClick={downloadCsv}><Download size={16}/> Export CSV</Button></div></div><div className="report-tabs" data-testid="report-tabs">{tabs.map(([id,label]) => <button key={id} className={tab === id ? 'active' : ''} data-testid={`reports-${id}-tab`} onClick={() => setTab(id)}>{label}</button>)}</div><div className="report-range"><span><CalendarDays size={17}/> DATE RANGE</span>{['today','week','month','custom'].map(option => <button className={range === option ? 'active' : ''} data-testid={`reports-range-${option}`} key={option} onClick={() => setRange(option)}>{option === 'today' ? 'Today' : option === 'week' ? 'This week' : option === 'month' ? 'This month' : 'Custom'}</button>)}{range === 'custom' && <div className="custom-date-inputs"><Input type="date" value={fromDate} data-testid="reports-from-date-input" onChange={e => setFromDate(e.target.value)}/><span>to</span><Input type="date" value={toDate} data-testid="reports-to-date-input" onChange={e => setToDate(e.target.value)}/></div>}</div>
    {tab === 'sales' && <><div className="report-stat-grid"><ReportStat label="PERIOD REVENUE" value={currency(period?.revenue)} info={`${period?.count || 0} bills in selected period`} id="sales-revenue"/><ReportStat label="TAX IN PERIOD" value={currency(period?.tax)} info="CGST + SGST + IGST" id="sales-tax"/><ReportStat label="MONTHLY REVENUE" value={currency(monthly?.revenue)} info={`${monthly?.billCount || 0} bills this month`} id="monthly-revenue"/><ReportStat label="GROSS PROFIT ESTIMATE" value={currency(period?.grossProfit)} info="Before expenses, based on entered purchase prices" id="gross-profit"/></div><section className="report-chart-section"><div className="dash-section-head"><div><span className="eyebrow">PERFORMANCE</span><h2>Sales over the last 7 days</h2></div></div><div className="chart-wrap">{overview && <ResponsiveContainer width="100%" height="100%"><BarChart data={overview.trend}><CartesianGrid stroke="#E2E8F0" vertical={false}/><XAxis dataKey="date" tickFormatter={x => x.slice(5)} axisLine={false} tickLine={false} tick={{ fill: '#64748B', fontSize: 11 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: '#64748B', fontSize: 11 }}/><Tooltip formatter={v => currency(v)} cursor={{ fill: '#F1F5F9' }} contentStyle={{background:'#fff',border:'1px solid #E2E8F0',color:'#0F172A',borderRadius:12}}/><Bar dataKey="sales" fill="#2563EB" radius={[6,6,0,0]} maxBarSize={48}/></BarChart></ResponsiveContainer>}</div></section><div className="form-section-title">BILLS IN SELECTED PERIOD</div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>INVOICE</th><th>CUSTOMER</th><th>DATE</th><th>PAYMENT</th><th>TOTAL</th></tr></thead><tbody>{period?.bills?.length ? period.bills.map(b => <tr key={b.id}><td>{b.number}</td><td>{b.customerName}</td><td>{dateOnly(b.date)}</td><td>{b.paymentMode}</td><td>{currency(b.grandTotal)}</td></tr>) : <tr><td colSpan="5"><div className="table-empty">No sales for this date range.</div></td></tr>}</tbody></table></div><p className="report-disclaimer">Profit estimates depend on purchase prices you enter for products. The imported catalogue starts with purchase price ₹0.</p></>}
    {tab === 'products' && <><div className="report-stat-grid"><ReportStat label="PRODUCTS SOLD" value={products.reduce((sum,p) => sum + p.quantity,0)} info="Units in selected period" id="products-sold"/><ReportStat label="PRODUCT REVENUE" value={currency(products.reduce((sum,p) => sum + p.revenue,0))} info="Including GST" id="product-revenue"/></div><div className="form-section-title">TOP SELLING PRODUCTS</div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>PRODUCT</th><th>QUANTITY</th><th>REVENUE</th></tr></thead><tbody>{products.length ? products.map((p,i) => <tr key={p.name}><td>{i + 1}. {p.name}</td><td>{p.quantity}</td><td>{currency(p.revenue)}</td></tr>) : <tr><td colSpan="3"><div className="table-empty">No product sales in this period.</div></td></tr>}</tbody></table></div></>}
    {tab === 'categories' && <><div className="report-stat-grid"><ReportStat label="CATEGORIES SOLD" value={categories.length} info="In selected period" id="categories-sold"/><ReportStat label="CATEGORY REVENUE" value={currency(categories.reduce((sum,c) => sum + c.revenue,0))} info="Including GST" id="category-revenue"/></div><div className="form-section-title">CATEGORY-WISE SALES</div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>CATEGORY</th><th>QUANTITY</th><th>REVENUE</th></tr></thead><tbody>{categories.length ? categories.map(c => <tr key={c.category}><td>{c.category}</td><td>{c.quantity}</td><td>{currency(c.revenue)}</td></tr>) : <tr><td colSpan="3"><div className="table-empty">No category sales in this period.</div></td></tr>}</tbody></table></div></>}
    {tab === 'gst' && <><div className="report-stat-grid"><ReportStat label="TAXABLE VALUE" value={currency(gst?.taxable)} info="After discounts" id="taxable-value"/><ReportStat label="CGST COLLECTED" value={currency(gst?.cgst)} info="Intra-state" id="cgst"/><ReportStat label="SGST COLLECTED" value={currency(gst?.sgst)} info="Intra-state" id="sgst"/><ReportStat label="IGST COLLECTED" value={currency(gst?.igst)} info="Inter-state" id="igst"/></div><div className="report-featured-total"><span>TOTAL GST COLLECTED</span><strong data-testid="reports-total-gst">{currency(gst?.totalTax)}</strong><small>Across {gst?.count || 0} invoices in the selected period.</small></div><p className="report-disclaimer"><TriangleAlert size={17}/> Verify every product’s HSN code and GST rate with your accountant before using these figures for filing.</p></>}
    {tab === 'stock' && <><div className="report-stat-grid"><ReportStat label="ACTIVE PRODUCTS" value={stock?.totalProducts || 0} info="In catalogue" id="stock-products"/><ReportStat label="LOW OR OUT OF STOCK" value={stock?.lowStock || 0} info="Need attention" id="stock-low"/><ReportStat label="AWAITING PHYSICAL COUNT" value={stock?.unCounted || 0} info="Initial stock not verified" id="stock-uncounted"/><ReportStat label="STOCK VALUE" value={currency(stock?.stockValue)} info="At purchase price" id="stock-value"/></div><div className="form-section-title">ITEMS TO CHECK</div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>PRODUCT</th><th>SKU</th><th>CURRENT</th><th>MINIMUM</th></tr></thead><tbody>{stock?.items?.map(p => <tr key={p.id}><td>{p.name}</td><td>{p.sku}</td><td>{p.currentStock}</td><td>{p.minStockLevel}</td></tr>)}</tbody></table></div></>}
    {tab === 'customers' && <><div className="report-stat-grid"><ReportStat label="CUSTOMERS" value={customers?.count || 0} info="Saved accounts" id="customer-count"/><ReportStat label="WITH DUES" value={customers?.withDues || 0} info="Outstanding payments" id="customers-dues"/><ReportStat label="TOTAL OUTSTANDING" value={currency(customers?.outstanding)} info="Khata balance" id="outstanding"/></div><div className="form-section-title">HIGHEST OUTSTANDING</div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>CUSTOMER</th><th>PHONE</th><th>BALANCE DUE</th></tr></thead><tbody>{customers?.topDue?.length ? customers.topDue.map(c => <tr key={c.id}><td>{c.name}</td><td>{c.phone}</td><td>{currency(c.balance)}</td></tr>) : <tr><td colSpan="3"><div className="table-empty">No customers to report on.</div></td></tr>}</tbody></table></div></>}
    {tab === 'quotations' && <div className="report-stat-grid"><ReportStat label="QUOTATIONS CREATED" value={quotes?.count || 0} info="All time" id="quotes-total"/><ReportStat label="CONVERTED TO BILLS" value={quotes?.converted || 0} info="Won business" id="quotes-converted"/><ReportStat label="CONVERSION RATE" value={`${quotes?.conversionRate || 0}%`} info="Quotes to bills" id="quotes-rate"/></div>}
  </div>;
}
function ReportStat({label,value,info,id}) { return <div className="report-stat" data-testid={`report-stat-${id}`}><span>{label}</span><strong>{value}</strong><small>{info}</small></div>; }